version: '3.8'

services:
  neo4j:
    image: neo4j:5.25-community
    container_name: neo4j-kg
    restart: unless-stopped
    ports:
      - "7474:7474"  # HTTP - Neo4j Browser
      - "7687:7687"  # Bolt - Python driver connection
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
      - ./neo4j/import:/var/lib/neo4j/import
      - ./neo4j/plugins:/plugins
    environment:
      # Authentication
      - NEO4J_AUTH=${NEO4J_USER:-neo4j}/${NEO4J_PASSWORD:-knowledge_graph_2024}

      # Memory settings (adjust based on your system)
      - NEO4J_server_memory_heap_initial__size=512m
      - NEO4J_server_memory_heap_max__size=2G
      - NEO4J_server_memory_pagecache_size=1G

      # APOC plugin configuration
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_dbms_security_procedures_allowlist=apoc.*

      # Performance tuning
      - NEO4J_dbms_connector_bolt_thread__pool__min__size=5
      - NEO4J_dbms_connector_bolt_thread__pool__max__size=400

      # Enable query logging (optional - useful for debugging)
      - NEO4J_dbms_logs_query_enabled=INFO
      - NEO4J_dbms_logs_query_threshold=1s

    networks:
      - crawler_default
      - default

    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider localhost:7474 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

networks:
  crawler_default:
    external: true
  default:
    name: neo4j-network
